### ISSUE TITLE
stuck on downloading chain

### ISSUE THREAD

**Issue by mplantsheer** [skepticoin/skepticoin#25]
NETWORK
Nr. of connected peers: 0

CHAIN
Height    71482
Date/time 2021-05-16T16:54:39

Waiting for fresh chain
Uncaught exception in LocalPeer.run()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 860, in run
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 850, in handle_selector_events
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 761, in handle_incoming_connection
  File "/usr/local/Cellar/python@3.9/3.9.2_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 293, in accept
OSError: [Errno 24] Too many open files

NETWORK
Nr. of connected peers: 62

**Comment by csheldrick** [comment]
This issue is related to reading the chain. 
In skepticoin/scripts/utils.py line 65 - 80:
`
def read_chain_from_disk():    print("Reading chain from disk")    coinstate = CoinState.zero()    for filename in sorted(os.listdir('chain')):        height = int(filename.split("-")[0])        if height % 1000 == 0:            print(filename)
        try:            block = Block.stream_deserialize(open(Path('chain') / filename, 'rb'))        except Exception as e:            raise Exception("Corrupted block on disk: %s" % filename) from e
        coinstate = coinstate.add_block_no_validation(block)
    return coinstate
`
Change to:
`def read_chain_from_disk():
    print("Reading chain from disk")
    coinstate = CoinState.zero()
    for filename in sorted(os.listdir('chain')):
        height = int(filename.split("-")[0])
        if height % 1000 == 0:
            print(filename)

        try:
            with open(Path("chain") / filename, 'rb') as inp:
                block = Block.stream_deserialize(inp)
        except Exception as e:
            raise Exception("Corrupted block on disk: %s" % filename) from e

        coinstate = coinstate.add_block_no_validation(block)

    return coinstate`

And now the file handles are correctly closed. So the files are no longer open.

**Comment by sashimi-houdini** [comment]
Thanks @csheldrick

**Comment by mplantsheer** [comment]
CHAIN
Height    73768
Date/time 2021-05-18T22:22:33

Waiting for fresh chain
Uncaught exception in LocalPeer.run()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 857, in run
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 839, in step_managers
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 98, in step
  File "/usr/local/lib/python3.9/site-packages/skepticoin/networking/peer.py", line 825, in start_outgoing_connection
  File "/usr/local/Cellar/python@3.9/3.9.2_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files

**Comment by sashimi-houdini** [comment]
Could you take a look at the list of open files whenever this occurs? The below SO page should be helpful.

https://stackoverflow.com/a/38732186/339144

**Comment by jamesPIX** [comment]
@sashimi-houdini I killed all my python processes and reran skepticoin-repl and got the same issue. I also installed skepti on a virtual machine and ended up getting the same error. Could if be caused by not properly closing the network connection while mining?

**Comment by lk16** [comment]
@atramos is this fixed in #41? If so, this should be closed.

**Comment by atramos** [comment]
I don't think the two are related.

**Comment by atramos** [comment]
@sashimi-houdini @lk16 are either of you able to reproduce this issue?

**Comment by sashimi-houdini** [comment]
I've never had this particular issue
