### ISSUE TITLE
MemoryError in peer.py, self.sent += ...

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#42]
Just noticed a new error in the logs, starting on 5/24:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/skepticoin/networking/peer.py", line 789, in handle_remote_peer_selector_event
    remote_peer.handle_can_send(sock)
  File "/usr/local/lib/python3.7/site-packages/skepticoin/networking/peer.py", line 466, in handle_can_send
    self.sent += self.send_buffer[:sent]
```

**Comment by atramos** [comment]
@sashimi-houdini what is the purpose of `self.sent`? It seems to just accumulate data until memory is full. Would there be any harm in removing this?
