### ISSUE TITLE
ValueError: Invalid file descriptor: -1

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#54]
This error does not appear to prevent normal operation of the miner, but has been happening more and more frequently:
```
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 848, in handle_remote_peer_selector_event
    remote_peer.handle_receive_data(recv_data)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 514, in handle_receive_data
    self.receiver.receive(data)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 363, in receive
    self.receive(b"")  # recurse to repeat (multiple messages could be received in a single socket read)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 358, in receive
    self.handle_message_data(self.buffer[:self.len])
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 369, in handle_message_data
    self.peer.handle_message_received(header, message)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 495, in handle_message_received
    return self.handle_get_peers_message_received(header, message)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 739, in handle_get_peers_message_received
    self.send_message(PeersMessage(peers), prev_header=header)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 459, in send_message
    self.check_message_backlog()
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 464, in check_message_backlog
    self.start_sending()
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev38+gf75d821-py3.8.egg/skepticoin/networking/peer.py", line 467, in start_sending
    self.local_peer.selector.modify(self.sock, selectors.EVENT_READ | selectors.EVENT_WRITE, data=self)
  File "/usr/lib64/python3.8/selectors.py", line 377, in modify
    key = self._fd_to_key[self._fileobj_lookup(fileobj)]
  File "/usr/lib64/python3.8/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib64/python3.8/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
```

**Comment by lk16** [comment]
"Good" to hear that this is on master, I thought this was a bug introduced by my own changes. 

I'll do some bisecting and find out what change caused this.

**Comment by atramos** [comment]
This is on the cloud-mining branch, which includes your fix to #42 that I merged in.

**Comment by atramos** [comment]
I have not seen this error in a long time. It was probably resolved by some combination of the fixes to #36, #45, and #71.

**Comment by atramos** [comment]
LOL as soon as I posted the above comment, I saw the error when using --log-to-stdout:
`2021-06-13 11:43:52,596       127.0.0.1 Disconnecting remote peer Invalid file descriptor: -1`

**Comment by atramos** [comment]
@sashimi-houdini what is the purpose of a peer connecting to itself?

**Comment by lk16** [comment]
I don't see how a peer connecting to itself makes any sense. Does preventing connecting to `127.0.0.1` fix this issue?
