### ISSUE TITLE
Miner crashed, due to too many open files?

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#61]
Running skepticoin v0.1.14 (latest release) on linux, with python 3.8.5, mining with 4 processes.

I got this error first on my linux box, though it looks a lot like #36.

```
Uncaught exception in LocalPeer.run()                                                                     
Traceback (most recent call last):                                                                        
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 857, in run                                                                                      
    self.step_managers(current_time)                                                                      
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 839, in step_managers                                                                            
    manager.step(current_time)                                                                            
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 98, in step                                                                                      
    self.local_peer.start_outgoing_connection(disconnected_peer)                                          
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 825, in start_outgoing_connection                                                                
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)                                              
  File "/usr/lib/python3.8/socket.py", line 231, in __init__                                                                                                                                                         
OSError: [Errno 24] Too many open files  
```

and then one of my miners crashed after mining a block:

```
miner  1 found block: 00085081-000148b4ddea2c58f670f540648a3955c08a11946239884d521f5eaea19dfdf9
miner  1: Stopping networking thread                                                                      
miner  1: Waiting for networking thread to stop                                                           
miner  1: Done; waiting for Python-exit                                                                   
Process Process-2:                                                                                        
Traceback (most recent call last):                                                                        
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 142, in broadcast_message
    peer.send_message(message)                                                                            
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 419, in send_message
    self.check_message_backlog()                                                                          
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 424, in check_message_backlog
    self.start_sending()                                                                                  
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 427, in start_sending
    self.local_peer.selector.modify(self.sock, selectors.EVENT_READ | selectors.EVENT_WRITE, data=self)
  File "/usr/lib/python3.8/selectors.py", line 379, in modify         
    raise KeyError(f"{fileobj!r} is not registered") from None        
KeyError: "<socket.socket fd=20, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 49274), raddr=('127.0.0.1', 2412)> is not registered"
                                                                                                          
During handling of the above exception, another exception occurred:   
                                                                                                          
Traceback (most recent call last):                                                                        
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()                                                                                            
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/scripts/mine.py", line 33, in run_miner
    miner()
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/scripts/mine.py", line 124, in __call__
    self.handle_mined_block(block)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/scripts/mine.py", line 93, in handle_mined_block
    self.thread.local_peer.network_manager.broadcast_block(block)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 133, in broadcast_block
    self.broadcast_message(DataMessage(DATA_BLOCK, block))
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/networking/peer.py", line 149, in broadcast_message
    self.logger.warning(traceback.format_exc())  # be loud... this is likely a programming error.
AttributeError: 'NetworkManager' object has no attribute 'logger'
```

**Comment by lk16** [comment]
I know `AttributeError: 'NetworkManager' object has no attribute 'logger'` is fixed already.
Also with the stripped-down miner merged now, the socket related error should not happen anymore either.

That leaves the too many open files error. The ~solution~ work around in PR #36 only affects windows, so we should probably also fix this for other platforms. Even a work-around is better than a crash. And then we implement a decent solution after that of course.

**Comment by lk16** [comment]
Duplicate of #25 I'm closing this.
