### ISSUE TITLE
It quit working

### ISSUE THREAD

**Issue by hunter-bidens-laptop** [skepticoin/skepticoin#82]
Getting this error now even though it worked this morning after updating:

https://imgur.com/a/1cRr6uC

**Comment by atramos** [comment]
As a troubleshooting step, try removing your chain.cache file. I have seen this error, but it is very rare.

**Comment by hunter-bidens-laptop** [comment]
Worked. Modifying the description to make this error searchable. Thanks!

**Comment by hunter-bidens-laptop** [comment]
Text of the error:

`<username>:skepticoin-mine
Reading cached chain
Reading chain from disk, starting height=85329, fresher=3619
Traceback (most recent call last):
File "/home/<username>/bin/skepticoin-mine", line 33, in <module>
    sys.exit(load_entry_point('skepticoin==0.1.16', 'console_scripts', 'skepticoin-mine')())
File "/home/<username>/lib/python3.9/site-packages/skepticoin/scripts/mine.py", line 6, in main
    miner_watcher()
File "/home/<username>/lib/python3.9/site-packages/skepticoin/mining.py", line 107, in __call__
    self.coinstate = read_chain_from_disk()
File "/home/<username>/lib/python3.9/site-packages/skepticoin/scripts/utils.py", line 135, in read_chain_from_disk
    coinstate = coinstate.add_block_no_validation(block)
File "/home/<username>/lib/python3.9/site-packages/skepticoin/coinstate.py", line 179, in add_block_no_validation
    unspent_transaction_outs = self.unspent_transaction_outs_by_hash[block.previous_block_hash]
KeyError: b"<somekeyname>"
`

The fix is to delete chain.cache:

`rm chain.cache`
