### ISSUE TITLE
Crash when mining after deleting chain folder

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#99]
I deleted my chain folder and the miner ran into this errror

```Traceback (most recent call last):
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 142, in __call__
    self.handle_received_message(queue_item)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 196, in handle_received_message
    handler(miner_id, data)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 245, in handle_scrypt_output_message
    with open(Path('chain') / block_filename(block), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'chain/00102316-00005b08fe2de19be185db3459b27cf293366f3b186927e60d1f51513e8314d9'
```

I didn't look into it, but looks like my miner crashed after mining a block.

**Comment by atramos** [comment]
I think I know the cause, let me check.

**Comment by atramos** [comment]
This bug only affects users that have removed their 'chain' folder. The linked PR should fix it, but I have to wait for a mined block for a proper test.
